version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/packages"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "nuget"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "dotnet-ef"
        update-types: ["version-update:semver-major"]
        versions: ["8.*", "9.*"] 